# Exercício com os dados do ENEM 2019

In [1]:
url = "http://download.inep.gov.br/microdados/microdados_enem_2019.zip"

In [2]:
import pandas as pd
import numpy as np
import zipfile
import requests
from io import BytesIO
import os

In [4]:
# Criar um diretório para armazenar os dados do ENEM
os.makedirs('exenem', exist_ok=True)

# Fazer a requisição do arquivo .zip
filebytes = BytesIO(
    requests.get(url, stream=True).content
)

# Extrair o conteúdo do zipfile

myzip = zipfile.ZipFile(filebytes)
myzip.extractall('exenem')

# Trabalhando com os dados do ENEM usando DASK

In [10]:
import dask.dataframe as dd
#usado quando falta memória. obs.: !pip install dask
#faz a leitura tardia, só quando realmente precisa

In [8]:
enem = dd.read_csv('exenem/DADOS/MICRODADOS_ENEM_2019.csv',
                   sep=';', 
                   decimal=',',
                   encoding='latin1')

In [9]:
enem.head(10)

,NU_INSCRICAO,NU_ANO,CO_MUNICIPIO_RESIDENCIA,NO_MUNICIPIO_RESIDENCIA,CO_UF_RESIDENCIA,SG_UF_RESIDENCIA,NU_IDADE,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,...,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023,Q024,Q025
0,190001004627,2019,1506807,Santarém,15,PA,21,M,1,3,...,A,A,A,C,B,A,D,A,B,A
1,190001004628,2019,1504059,Mãe do Rio,15,PA,16,F,1,3,...,A,A,A,B,B,A,B,A,A,A
2,190001004629,2019,1505502,Paragominas,15,PA,18,F,1,1,...,B,A,A,D,B,B,D,A,C,B
3,190001004630,2019,1507706,São Sebastião da Boa Vista,15,PA,23,M,0,3,...,A,A,A,C,A,A,D,A,A,A
4,190001004631,2019,1503903,Juruti,15,PA,23,M,1,3,...,A,A,A,B,A,A,D,A,A,A
5,190001004632,2019,1500800,Ananindeua,15,PA,31,M,1,1,...,A,A,A,B,A,A,D,A,A,A
6,190001004633,2019,1504208,Marabá,15,PA,30,F,2,3,...,A,A,A,B,A,A,B,A,A,B
7,190001004634,2019,1501402,Belém,15,PA,26,F,0,3,...,A,A,A,B,A,A,B,A,A,A
8,190001004635,2019,1503606,Itaituba,15,PA,19,M,1,3,...,A,A,A,A,A,A,C,A,A,B
9,190001004636,2019,1507607,São Miguel do Guamá,15,PA,17,F,1,2,...,A,A,A,B,A,A,B,A,A,A

In [11]:
enem = enem.loc[
    enem.SG_UF_RESIDENCIA == 'MG'
]

In [12]:
enem.head(10)

,NU_INSCRICAO,NU_ANO,CO_MUNICIPIO_RESIDENCIA,NO_MUNICIPIO_RESIDENCIA,CO_UF_RESIDENCIA,SG_UF_RESIDENCIA,NU_IDADE,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,...,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023,Q024,Q025
1044,190001005671,2019,3170206,Uberlândia,31,MG,21,M,1,1,...,B,A,A,D,A,A,D,B,B,B
5234,190001009861,2019,3111705,Canaã,31,MG,20,M,1,1,...,A,A,A,B,A,A,C,A,A,A
16995,190001021622,2019,3104007,Araxá,31,MG,24,M,1,2,...,A,A,A,C,B,A,C,A,A,B
22008,190001026636,2019,3106200,Belo Horizonte,31,MG,33,M,1,1,...,B,A,B,B,A,A,D,A,D,B
22114,190001026742,2019,3162401,São João da Ponte,31,MG,23,M,1,3,...,A,A,A,B,B,A,C,A,B,A
41418,190001046046,2019,3124302,Espinosa,31,MG,22,M,1,3,...,B,A,A,C,B,A,E,A,B,B
41845,190001046473,2019,3169307,Três Corações,31,MG,19,F,1,3,...,B,A,A,B,B,B,E,A,B,B
48454,190001053082,2019,3106705,Betim,31,MG,20,M,1,3,...,B,A,A,B,A,A,D,A,B,B
51498,190001056126,2019,3143302,Montes Claros,31,MG,23,F,1,2,...,B,A,A,B,A,A,C,A,C,B
54094,190001058722,2019,3169307,Três Corações,31,MG,18,F,1,1,...,B,A,A,C,B,A,D,A,C,B

# Ingestão dos dados no sql Server

In [13]:
# Transformar o enem em um df do tipo pandas
enem = enem.compute()

In [19]:
enem.type()

AttributeError: 'DataFrame' object has no attribute 'type'

In [18]:
enem.shape

(538896, 136)

In [22]:
import sqlalchemy
engine = sqlalchemy.create_engine(
    "mssql+pyodbc://SA:@Somar100@127.0.0.1/enadeMG2019?driver=ODBC+Driver+17+for+SQL+Server"
)

In [23]:
%%time
enem.to_sql('desempenhoMG', con=engine, index=False, if_exists='append', chunksize=1000)

DBAPIError: (pyodbc.Error) ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 17 for SQL Server' : file not found (0) (SQLDriverConnect)")
(Background on this error at: http://sqlalche.me/e/13/dbapi)